apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subscriber-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jreb-123/poc-nats-wasm-critical.git
    targetRevision: main
    path: charts/subscriber
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
